/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvancedRequestBuilder: typeof import('./components/requestBuilder/AdvancedRequestBuilder.vue')['default']
    AdvancedRequestForm: typeof import('./components/requestBuilder/AdvancedRequestForm.vue')['default']
    CardList: typeof import('./components/CardList.vue')['default']
    ConditionForm: typeof import('./components/requestBuilder/ConditionForm.vue')['default']
    Controls: typeof import('./components/map/Controls/Controls.vue')['default']
    copy: typeof import('./components/requestBuilder/FilterForm copy.vue')['default']
    DeleteModal: typeof import('./components/Modals/DeleteModal.vue')['default']
    Drawing: typeof import('./components/map/Controls/Drawing.vue')['default']
    DsfrAccordion: typeof import('@gouvminint/vue-dsfr')['DsfrAccordion']
    DsfrAccordionsGroup: typeof import('@gouvminint/vue-dsfr')['DsfrAccordionsGroup']
    DsfrButton: typeof import('@gouvminint/vue-dsfr')['DsfrButton']
    DsfrCheckbox: typeof import('@gouvminint/vue-dsfr')['DsfrCheckbox']
    DsfrDataTable: typeof import('@gouvminint/vue-dsfr')['DsfrDataTable']
    DsfrSearchBar: typeof import('@gouvminint/vue-dsfr')['DsfrSearchBar']
    DsfrSelect: typeof import('@gouvminint/vue-dsfr')['DsfrSelect']
    ExpertRequestBuilder: typeof import('./components/requestBuilder/ExpertRequestBuilder.vue')['default']
    ExtentInteraction: typeof import('./components/map/Interactions/extentInteraction.vue')['default']
    ExtractibleGrid: typeof import('./components/template-grid/ExtractibleGrid.vue')['default']
    ExtractionList: typeof import('./components/ExtractionList.vue')['default']
    ExtractionListElement: typeof import('./components/ExtractionListElement.vue')['default']
    FilterForm: typeof import('./components/requestBuilder/FilterForm.vue')['default']
    'FilterForm copy': typeof import('./components/requestBuilder/FilterForm copy.vue')['default']
    FilterGroup: typeof import('./components/requestBuilder/FilterGroup.vue')['default']
    Layer: typeof import('./components/map/Layer.vue')['default']
    LayerImport: typeof import('./components/map/Controls/LayerImport.vue')['default']
    Map: typeof import('./components/map/Map.vue')['default']
    Modals: typeof import('./components/Modals.vue')['default']
    MyExtractionSkeleton: typeof import('./components/template-grid/MyExtractionSkeleton.vue')['default']
    NameExtractionModal: typeof import('./components/Modals/NameExtractionModal.vue')['default']
    Patience: typeof import('./components/utils/Patience.vue')['default']
    RelaunchModal: typeof import('./components/Modals/RelaunchModal.vue')['default']
    RequestBuilder: typeof import('./components/requestBuilder/RequestBuilder.vue')['default']
    RequestForm: typeof import('./components/requestBuilder/RequestForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchableCardList: typeof import('./components/SearchableCardList.vue')['default']
    SearchEngine: typeof import('./components/map/Controls/SearchEngine.vue')['default']
    StoreData: typeof import('./components/async-data/StoreData.vue')['default']
    SuccessModal: typeof import('./components/Modals/SuccessModal.vue')['default']
    TableAttributeSelector: typeof import('./components/requestBuilder/TableAttributeSelector.vue')['default']
    TableAttSelector: typeof import('./components/requestBuilder/TableAttSelector.vue')['default']
    TableSelector: typeof import('./components/requestBuilder/TableSelector.vue')['default']
    VectorLayer: typeof import('./components/map/VectorLayer.vue')['default']
    View: typeof import('./components/map/View.vue')['default']
    Zoom: typeof import('./components/map/Controls/Zoom.vue')['default']
  }
}
